title: Bhanu Prakash
logo: /Images/profile_pic.png
description: Hello, I am Bhanu Prakash, a Computer Science graduate student at Texas A&M University, Kingsville, with a passion for data analysis, dashboard creation, and crafting insightful projects in Power BI.
show_downloads: false
theme: jekyll-theme-minimal
author: Bhanu Prakash
keywords: Data Analysis, Power BI, Portfolio, Computer Science
url: https://bhanuprakash000.github.io/sample/
