title: Bhanu Prakash
logo: /Images/Headshot_pic.png
description: Hello, my name is Bhanu Prakash, and I'm currently studying Computer Science at the Texas A&M University at Kingsville. I love playing with Data, creating dashboards, and making cool projects in PowerBI.
show_downloads: false
theme: jekyll-theme-minimal
